### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/benutzer
Content-Type: application/json

{
  "mail": null,
  "tel": "+43 651 587855"
}

###

GET http://localhost:8080/api/benutzer
Content-Type: */*

###

POST http://localhost:8080/api/benutzer/verify-email?token=e0509c5f-8046-40da-a902-448fead69f81
Content-Type: */*
