### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/benutzer
Content-Type: application/json

{
  "mail": null,
  "tel": "+43 651 587855"
}

###

GET http://localhost:8080/api/benutzer
Content-Type: */*

###

POST http://localhost:8080/api/benutzer/verify-email?token=a86bc05c-926f-46e2-b0da-429de1278dac
Content-Type: */*
