### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/api/activitylog
Content-Type: */*

###

GET http://localhost:8080/api/activitylog/1
Content-Type: */*

###

GET http://localhost:8080/api/activitylog/all
Content-Type: */*