### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/api/notifications
Content-Type: */*

###

GET http://localhost:8080/api/notifications/benutzer/1
Content-Type: application/json

###

GET http://localhost:8080/api/notifications/mail/alice.muster@htl.at
Content-Type: application/json

