-- Import / Schema-Skript für das ERD (Benutzer, Thema, Status, Kategorie, Feedback, Bild, feedback_kategorie)
-- Erstellt Tabellen, Foreign Keys und fügt Beispiel-Daten ein.
-- Läuft auf PostgreSQL.

-- Reihenfolge beachten: erst dependent objects löschen, dann neu anlegen
DROP TABLE IF EXISTS feedback_kategorie;
DROP TABLE IF EXISTS bild;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS kategorie;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS thema;
DROP TABLE IF EXISTS benutzer;

-- Benutzer (ANGEPASST: mail, tel statt vorname, nachname)
CREATE TABLE benutzer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          mail VARCHAR(255),
                          tel VARCHAR(50),
                          rolle VARCHAR(50) NOT NULL
);

-- Thema
CREATE TABLE thema (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       bezeichnung VARCHAR(150) NOT NULL
);

-- Status
CREATE TABLE status (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        bezeichnung VARCHAR(100) NOT NULL
);

-- Kategorie
CREATE TABLE kategorie (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           bezeichnung VARCHAR(150) NOT NULL
);

-- Feedback
CREATE TABLE feedback (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          betreff VARCHAR(255) NOT NULL,
                          beschreibung TEXT NOT NULL,
                          typ VARCHAR(100) NOT NULL,
                          status_id BIGINT REFERENCES status(id) ON DELETE SET NULL,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                          updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                          user_id BIGINT REFERENCES benutzer(id) ON DELETE SET NULL,
                          thema_id BIGINT REFERENCES thema(id) ON DELETE SET NULL
);

-- Join-Table Feedback <-> Kategorie (ManyToMany)
CREATE TABLE feedback_kategorie (
                                    feedback_id BIGINT NOT NULL REFERENCES feedback(id) ON DELETE CASCADE,
                                    kategorie_id BIGINT NOT NULL REFERENCES kategorie(id) ON DELETE CASCADE,
                                    PRIMARY KEY (feedback_id, kategorie_id)
);

-- Indexes (optional, für bessere Performance bei Joins / Lookups)
CREATE INDEX idx_feedback_status ON feedback(status_id);
CREATE INDEX idx_feedback_user ON feedback(user_id);
CREATE INDEX idx_feedback_thema ON feedback(thema_id);
CREATE INDEX idx_feedback_kategorie_k ON feedback_kategorie(kategorie_id);

-- -------------------------
-- Beispiel-Daten einfügen
-- -------------------------

-- Statuswerte
INSERT INTO status (bezeichnung) VALUES
                                     ('Neu'),
                                     ('In Bearbeitung'),
                                     ('Erledigt');

-- Themen
INSERT INTO thema (bezeichnung) VALUES
                                    ('Infrastruktur'),
                                    ('Service'),
                                    ('IT');

-- Kategorien
INSERT INTO kategorie (bezeichnung) VALUES
                                        ('Sicherheit'),
                                        ('Sauberkeit'),
                                        ('Funktionalität'),
                                        ('Sonstiges');

-- Benutzer (ANGEPASST: mit mail und tel)
INSERT INTO benutzer (mail, tel, rolle) VALUES
                                            ('alice.muster@htl.at', '+43 664 1234567', 'student'),
                                            ('bob.beispiel@htl.at', '+43 664 2345678', 'student'),
                                            ('charlie.test@htl.at', '+43 664 3456789', 'lehrer'),
                                            ('diana.demo@htl.at', '+43 664 4567890', 'admin');

-- Beispiel-Feedbacks
INSERT INTO feedback (betreff, beschreibung, typ, status_id, created_at, updated_at, user_id, thema_id)
VALUES
    ('Kaputte Tür', 'Die Tür im Raum 12 klemmt und lässt sich schwer öffnen.', 'Beschwerde', 1, NOW(), NOW(), 1, 1),
    ('Sauberkeit Mensa', 'In der Mensa liegen oft Essensreste auf dem Boden.', 'Beschwerde', 2, NOW(), NOW(), 2, 2),
    ('Tolles Update', 'Das neue Login-Feature funktioniert sehr gut.', 'Lob', 3, NOW(), NOW(), 3, 3),
    ('WLAN Aussetzer', 'Das WLAN bricht im Gebäude C mehrfach täglich ab.', 'Beschwerde', 1, NOW(), NOW(), 1, 3);

-- Kategorien-Zuordnungen (ManyToMany)
INSERT INTO feedback_kategorie (feedback_id, kategorie_id) VALUES
                                                               (1, 3), -- Kaputte Tür -> Funktionalität
                                                               (1, 4), -- Kaputte Tür -> Sonstiges
                                                               (2, 2), -- Sauberkeit Mensa -> Sauberkeit
                                                               (3, 4), -- Tolles Update -> Sonstiges
                                                               (4, 1); -- WLAN Aussetzer -> Sicherheit

-- -------------------------
-- Sequenzen / Identitys auf Max setzen
-- (setzt die internal sequence so dass nächste ID > max(id))
-- -------------------------
SELECT setval(pg_get_serial_sequence('benutzer','id'),
              GREATEST((SELECT COALESCE(MAX(id),0) FROM benutzer), 1), true);

SELECT setval(pg_get_serial_sequence('thema','id'),
              GREATEST((SELECT COALESCE(MAX(id),0) FROM thema), 1), true);

SELECT setval(pg_get_serial_sequence('status','id'),
              GREATEST((SELECT COALESCE(MAX(id),0) FROM status), 1), true);

SELECT setval(pg_get_serial_sequence('kategorie','id'),
              GREATEST((SELECT COALESCE(MAX(id),0) FROM kategorie), 1), true);

SELECT setval(pg_get_serial_sequence('feedback','id'),
              GREATEST((SELECT COALESCE(MAX(id),0) FROM feedback), 1), true);

-- Ende des Import-Skripts