-- Import / Schema-Skript (erweitert um Mitarbeiter-Verwaltung)
-- Läuft auf PostgreSQL.

-- Reihenfolge beachten:  erst dependent objects löschen, dann neu anlegen
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS mitarbeiter CASCADE;
DROP TABLE IF EXISTS bild CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS kategorie CASCADE;
DROP TABLE IF EXISTS thema CASCADE;
DROP TABLE IF EXISTS benutzer CASCADE;

-- Benutzer (Basis-Tabelle für alle User-Typen)
CREATE TABLE benutzer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          mail VARCHAR(255),
                          tel VARCHAR(50),
                          rolle VARCHAR(50) NOT NULL,
                          CONSTRAINT benutzer_tel_unique UNIQUE (tel),
                          CONSTRAINT benutzer_mail_unique UNIQUE (mail)
);

-- Mitarbeiter (erweiterte Tabelle nur für Mitarbeiter)
CREATE TABLE mitarbeiter (
                             id BIGINT PRIMARY KEY,
                             benutzername VARCHAR(100) NOT NULL UNIQUE,
                             passwort VARCHAR(255) NOT NULL,
                             vorname VARCHAR(100) NOT NULL,
                             nachname VARCHAR(100) NOT NULL,
                             abteilung VARCHAR(100),
                             aktiv BOOLEAN NOT NULL DEFAULT TRUE,
                             letzter_login TIMESTAMP WITHOUT TIME ZONE,
                             CONSTRAINT fk_mitarbeiter_benutzer
                                 FOREIGN KEY (id) REFERENCES benutzer(id) ON DELETE CASCADE
);

-- Thema (bleibt bestehen, aber Feedback referenziert es nicht mehr)
CREATE TABLE thema (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       bezeichnung VARCHAR(150) NOT NULL
);

-- Kategorie (bleibt bestehen)
CREATE TABLE kategorie (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           bezeichnung VARCHAR(150) NOT NULL
);

-- Feedback (ohne thema_id)
CREATE TABLE feedback (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          betreff VARCHAR(255) NOT NULL,
                          beschreibung TEXT NOT NULL,
                          typ VARCHAR(100) NOT NULL,
                          status VARCHAR(100) NOT NULL,
                          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                          updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                          user_id BIGINT REFERENCES benutzer(id) ON DELETE SET NULL
);

-- Bild (falls du Bilder benutzt)
CREATE TABLE bild (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      pfad VARCHAR(1024) NOT NULL,
                      beschreibung TEXT,
                      feedback_id BIGINT REFERENCES feedback(id) ON DELETE CASCADE
);

-- Notification Tabelle
CREATE TABLE notification (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              typ VARCHAR(50) NOT NULL,
                              nachricht TEXT NOT NULL,
                              betreff VARCHAR(255),
                              gelesen BOOLEAN NOT NULL DEFAULT FALSE,
                              created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                              benutzer_id BIGINT REFERENCES benutzer(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_feedback_user ON feedback(user_id);
CREATE INDEX idx_notification_benutzer ON notification(benutzer_id);
CREATE INDEX idx_notification_gelesen ON notification(gelesen);
CREATE INDEX idx_mitarbeiter_benutzername ON mitarbeiter(benutzername);
CREATE INDEX idx_mitarbeiter_aktiv ON mitarbeiter(aktiv);

-- -------------------------
-- Beispiel-Daten einfügen
-- -------------------------

-- Themen
INSERT INTO thema (bezeichnung) VALUES
                                    ('Infrastruktur'),
                                    ('Service'),
                                    ('IT');

-- Kategorien
INSERT INTO kategorie (bezeichnung) VALUES
                                        ('Sicherheit'),
                                        ('Sauberkeit'),
                                        ('Funktionalität'),
                                        ('Sonstiges');

-- -------------------------
-- Normale Benutzer (Bürger)
-- -------------------------
INSERT INTO benutzer (mail, tel, rolle) VALUES
                                            ('alice.muster@htl.at', '+43 664 1234567', 'nutzer'),
                                            ('bob.beispiel@htl.at', '+43 664 2345678', 'nutzer'),
                                            ('charlie.test@htl.at', '+43 664 3456789', 'nutzer'),
                                            ('diana.demo@gmail.com', '+43 664 4567890', 'nutzer'),
                                            ('erik.example@outlook.com', '+43 664 5678901', 'nutzer');

-- -------------------------
-- Mitarbeiter
-- -------------------------

-- Admin Mitarbeiter
INSERT INTO benutzer (mail, tel, rolle) VALUES
    ('admin@teamwels.at', '+43 664 9990001', 'mitarbeiter');

INSERT INTO mitarbeiter (id, benutzername, passwort, vorname, nachname, abteilung, aktiv) VALUES
    (
        (SELECT id FROM benutzer WHERE mail = 'admin@teamwels.at'),
        'admin',
        'admin123',
        'Max',
        'Administrator',
        'IT',
        true
    );

-- IT Support Mitarbeiter
INSERT INTO benutzer (mail, tel, rolle) VALUES
    ('lisa.tech@teamwels.at', '+43 664 9990002', 'mitarbeiter');

INSERT INTO mitarbeiter (id, benutzername, passwort, vorname, nachname, abteilung, aktiv) VALUES
    (
        (SELECT id FROM benutzer WHERE mail = 'lisa. tech@teamwels.at'),
        'lisa.tech',
        'techSupport2024',
        'Lisa',
        'Techniker',
        'IT Support',
        true
    );

-- Facility Management Mitarbeiter
INSERT INTO benutzer (mail, tel, rolle) VALUES
    ('thomas.bau@teamwels.at', '+43 664 9990003', 'mitarbeiter');

INSERT INTO mitarbeiter (id, benutzername, passwort, vorname, nachname, abteilung, aktiv) VALUES
    (
        (SELECT id FROM benutzer WHERE mail = 'thomas.bau@teamwels.at'),
        'thomas.bau',
        'facility2024',
        'Thomas',
        'Bauer',
        'Facility Management',
        true
    );

-- Service Desk Mitarbeiterin
INSERT INTO benutzer (mail, tel, rolle) VALUES
    ('anna.service@teamwels.at', '+43 664 9990004', 'mitarbeiter');

INSERT INTO mitarbeiter (id, benutzername, passwort, vorname, nachname, abteilung, aktiv) VALUES
    (
        (SELECT id FROM benutzer WHERE mail = 'anna.service@teamwels.at'),
        'anna.service',
        'service2024',
        'Anna',
        'Müller',
        'Service Desk',
        true
    );

-- Inaktiver Mitarbeiter (zum Testen)
INSERT INTO benutzer (mail, tel, rolle) VALUES
    ('ex. worker@teamwels.at', '+43 664 9990099', 'mitarbeiter');

INSERT INTO mitarbeiter (id, benutzername, passwort, vorname, nachname, abteilung, aktiv) VALUES
    (
        (SELECT id FROM benutzer WHERE mail = 'ex.worker@teamwels.at'),
        'ex.worker',
        'old2024',
        'Franz',
        'Alt',
        'Verwaltung',
        false  -- Nicht mehr aktiv
    );

-- -------------------------
-- Feedback (von normalen Benutzern)
-- -------------------------
INSERT INTO feedback (betreff, beschreibung, typ, status, user_id) VALUES
                                                                       (
                                                                           'Defekte Straßenbeleuchtung',
                                                                           'Die Straßenbeleuchtung in der Hauptstraße 45 ist seit 3 Tagen defekt.',
                                                                           'Beschwerde',
                                                                           'OFFEN',
                                                                           (SELECT id FROM benutzer WHERE mail = 'alice.muster@htl.at')
                                                                       ),
                                                                       (
                                                                           'Toller neuer Spielplatz',
                                                                           'Der neue Spielplatz im Stadtpark ist wirklich gelungen!  Meine Kinder lieben ihn.',
                                                                           'Lob',
                                                                           'BEARBEITET',
                                                                           (SELECT id FROM benutzer WHERE mail = 'bob.beispiel@htl. at')
                                                                       ),
                                                                       (
                                                                           'Müll nicht abgeholt',
                                                                           'Die Mülltonne wurde diese Woche nicht geleert.',
                                                                           'Beschwerde',
                                                                           'IN_BEARBEITUNG',
                                                                           (SELECT id FROM benutzer WHERE mail = 'charlie.test@htl. at')
                                                                       ),
                                                                       (
                                                                           'Anfrage zu Öffnungszeiten',
                                                                           'Sind die Öffnungszeiten des Bürgerservices auch am Samstag? ',
                                                                           'Anfrage',
                                                                           'OFFEN',
                                                                           (SELECT id FROM benutzer WHERE mail = 'diana.demo@gmail.com')
                                                                       ),
                                                                       (
                                                                           'Schlagloch in der Parkstraße',
                                                                           'Großes Schlagloch vor Hausnummer 12. Sehr gefährlich für Radfahrer! ',
                                                                           'Beschwerde',
                                                                           'OFFEN',
                                                                           (SELECT id FROM benutzer WHERE mail = 'erik. example@outlook.com')
                                                                       );

-- -------------------------
-- Notifications
-- -------------------------
INSERT INTO notification (typ, betreff, nachricht, gelesen, benutzer_id) VALUES
                                                                             (
                                                                                 'EMAIL',
                                                                                 'Feedback Status-Update:  Defekte Straßenbeleuchtung',
                                                                                 'Sehr geehrte/r Benutzer, Ihr Feedback "Defekte Straßenbeleuchtung" ist bei uns angekommen. Mit freundlichen Grüßen, Ihr Team Wels',
                                                                                 false,
                                                                                 (SELECT id FROM benutzer WHERE mail = 'alice. muster@htl.at')
                                                                             ),
                                                                             (
                                                                                 'SMS',
                                                                                 null,
                                                                                 'Feedback:  "Defekte Straßenbeleuchtung" ist bei uns angekommen',
                                                                                 false,
                                                                                 (SELECT id FROM benutzer WHERE mail = 'alice. muster@htl.at')
                                                                             ),
                                                                             (
                                                                                 'EMAIL',
                                                                                 'Feedback Status-Update: Toller neuer Spielplatz',
                                                                                 'Sehr geehrte/r Benutzer, Ihr Feedback "Toller neuer Spielplatz" wurde bearbeitet. Mit freundlichen Grüßen, Ihr Team Wels',
                                                                                 true,
                                                                                 (SELECT id FROM benutzer WHERE mail = 'bob.beispiel@htl.at')
                                                                             ),
                                                                             (
                                                                                 'EMAIL',
                                                                                 'Feedback Status-Update: Müll nicht abgeholt',
                                                                                 'Sehr geehrte/r Benutzer, Ihr Feedback "Müll nicht abgeholt" wird derzeit bearbeitet. Mit freundlichen Grüßen, Ihr Team Wels',
                                                                                 false,
                                                                                 (SELECT id FROM benutzer WHERE mail = 'charlie.test@htl.at')
                                                                             );